language: php

sudo: false

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

env:
  - # default environment without variables
  - COMPOSER_DEPENDENCIES_OPTIONS="--prefer-lowest --prefer-stable"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - composer self-update

install:
  - composer update --no-interaction --no-suggest --prefer-source ${COMPOSER_DEPENDENCIES_OPTIONS}

script:
  - bin/phing ci-build

after_success:
  - if [ "${TRAVIS_ALLOW_FAILURE}" = false ]; then
        wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.0/coveralls.phar
        && php coveralls.phar --verbose --config build/coveralls.yml
        || true;
    fi
